name: sample-workflow

on: 
  push:
    branches: [main]

jobs:
  job1:
    runs-on: shima_runner
    steps:
      - name: checks-out your repository under $GITHUB_WORKSPACE
        uses: actions/checkout@v2
      - name: use echo command
        run: echo "sample-workflow"